#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════
# easyBacklog — one-shot setup script (Linux / macOS)
#
# What this script does:
#   1. Checks that Docker is installed and running
#   2. Creates an easybacklog/ directory and enters it
#   3. Downloads docker-compose.yml from this GitHub release
#   4. Generates a .env file with secure random tokens
#   5. Pulls the pre-built Docker images
#   6. Starts all services (PostgreSQL, Redis, Rails, Sidekiq)
#   7. Waits for the web server to become ready
#   8. Initialises the database (schema + seed data)
#   9. Prints the URL and demo credentials
#
# Usage:
#   curl -fsSL https://github.com/mattanmr/easybacklog/releases/latest/download/setup.sh | bash
#
#   # or, to skip loading the demo data:
#   curl -fsSL https://github.com/mattanmr/easybacklog/releases/latest/download/setup.sh \
#     | bash -s -- --skip-sample-data
#
# Requirements: Docker Desktop (macOS/Windows) or Docker Engine + Docker
#               Compose plugin (Linux). curl and openssl must be available.
# ══════════════════════════════════════════════════════════════════════════

set -euo pipefail

# ── Parse args ───────────────────────────────────────────────────────────
SKIP_SAMPLE_DATA=false
for arg in "$@"; do
  case "$arg" in
    --skip-sample-data) SKIP_SAMPLE_DATA=true ;;
  esac
done

# ── Constants ────────────────────────────────────────────────────────────
RELEASE_BASE_URL="https://github.com/mattanmr/easybacklog/releases/latest/download"
INSTALL_DIR="easybacklog"
APP_URL="http://localhost:3000"
HEALTH_URL="${APP_URL}/status"
HEALTH_TIMEOUT=120   # seconds to wait for the web server
COMPOSE_PROJECT="easybacklog"

# ── Colors ───────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m'

# ── Helpers ──────────────────────────────────────────────────────────────
info()    { echo -e "${CYAN}▶${NC}  $*"; }
success() { echo -e "${GREEN}✔${NC}  $*"; }
warn()    { echo -e "${YELLOW}⚠${NC}  $*"; }
die()     { echo -e "${RED}✖${NC}  $*" >&2; exit 1; }

step() {
  echo ""
  echo -e "${BOLD}── Step $1: $2${NC}"
}

# ── Step 1: Check Docker ─────────────────────────────────────────────────
step 1 "Checking prerequisites"

if ! command -v docker &>/dev/null; then
  die "Docker not found. Install Docker Desktop from https://www.docker.com/products/docker-desktop/ and try again."
fi

if ! docker info &>/dev/null; then
  die "Docker is installed but not running. Start Docker Desktop and try again."
fi

if ! docker compose version &>/dev/null; then
  die "Docker Compose plugin not found. Update Docker Desktop to a recent version (it includes Compose v2)."
fi

if ! command -v openssl &>/dev/null; then
  die "openssl not found. Install it via your package manager (e.g. 'sudo apt install openssl' or 'brew install openssl')."
fi

success "Docker $(docker --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1) is running"

# ── Step 2: Create install directory ─────────────────────────────────────
step 2 "Creating install directory"

if [[ -d "$INSTALL_DIR" ]]; then
  warn "Directory './$INSTALL_DIR' already exists — continuing inside it."
else
  mkdir "$INSTALL_DIR"
  success "Created './$INSTALL_DIR'"
fi
cd "$INSTALL_DIR"

# ── Step 3: Download docker-compose.yml ──────────────────────────────────
step 3 "Downloading docker-compose.yml"

if [[ -f "docker-compose.yml" ]]; then
  warn "docker-compose.yml already exists — skipping download."
else
  if ! curl -fsSL "${RELEASE_BASE_URL}/docker-compose.yml" -o docker-compose.yml; then
    die "Download failed. Check your internet connection and try again."
  fi
  success "Downloaded docker-compose.yml"
fi

# ── Step 4: Generate .env file ───────────────────────────────────────────
step 4 "Generating .env file"

if [[ -f ".env" ]]; then
  warn ".env already exists — skipping generation. Delete it and re-run to regenerate."
else
  SECRET_TOKEN=$(openssl rand -hex 64)
  DEVISE_PEPPER=$(openssl rand -hex 64)

  cat > .env <<EOF
# easyBacklog environment configuration
# Generated by setup.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
# ─────────────────────────────────────────────────────────
# SECRET_TOKEN    — Rails session secret. Must be ≥30 chars.
#                   Changing this invalidates all active sessions.
SECRET_TOKEN=${SECRET_TOKEN}

# DEVISE_PEPPER   — Password hashing pepper. Must be ≥30 chars.
#                   Never change this once users have been created
#                   (it would invalidate all passwords).
DEVISE_PEPPER=${DEVISE_PEPPER}

# DB_PASSWORD     — PostgreSQL password for the 'postgres' user.
#                   Change before exposing the database port publicly.
DB_PASSWORD=password
EOF

  success "Generated .env with secure random tokens"
fi

# ── Step 5: Pull images ───────────────────────────────────────────────────
step 5 "Pulling Docker images (this may take a minute on first run)"

if ! docker compose -p "$COMPOSE_PROJECT" pull; then
  die "Image pull failed. Check your internet connection and try again."
fi
success "Images pulled"

# ── Step 6: Start services ────────────────────────────────────────────────
step 6 "Starting services"

if ! docker compose -p "$COMPOSE_PROJECT" up -d; then
  die "Failed to start services. Run 'docker compose logs' inside ./${INSTALL_DIR} for details."
fi
success "Services started (db, redis, web, sidekiq)"

# ── Step 7: Wait for web server ───────────────────────────────────────────
step 7 "Waiting for the web server to become ready (timeout: ${HEALTH_TIMEOUT}s)"

elapsed=0
while [[ $elapsed -lt $HEALTH_TIMEOUT ]]; do
  if curl -sf "$HEALTH_URL" -o /dev/null 2>/dev/null; then
    success "Web server is ready (${elapsed}s)"
    break
  fi
  sleep 5
  elapsed=$((elapsed + 5))
  echo -n "."
done

if [[ $elapsed -ge $HEALTH_TIMEOUT ]]; then
  echo ""
  warn "Web server did not respond within ${HEALTH_TIMEOUT}s."
  warn "Check logs with: docker compose -p ${COMPOSE_PROJECT} logs -f web"
  warn "The database init commands below may still work once it starts."
fi

# ── Step 8: Initialise the database ──────────────────────────────────────
step 8 "Initialising the database (first-run only)"

info "Loading schema…"
docker compose -p "$COMPOSE_PROJECT" exec -T web bundle exec rake db:schema:load

info "Loading seed data…"
docker compose -p "$COMPOSE_PROJECT" exec -T web bundle exec rake db:seed

if [[ "$SKIP_SAMPLE_DATA" == "false" ]]; then
  info "Loading sample data (demo account + backlog)…"
  docker compose -p "$COMPOSE_PROJECT" exec -T web bundle exec rake db:seed:sample
  success "Database initialised with schema, seeds, and sample data"
else
  success "Database initialised with schema and seeds (sample data skipped)"
fi

# ── Step 9: Done ──────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}══════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  easyBacklog is ready!${NC}"
echo -e "${GREEN}${BOLD}══════════════════════════════════════════════${NC}"
echo ""
echo -e "  URL:       ${BOLD}${APP_URL}${NC}"
if [[ "$SKIP_SAMPLE_DATA" == "false" ]]; then
  echo -e "  Email:     demo@example.com"
  echo -e "  Password:  password123"
  echo ""
  echo -e "  (Or sign up for a new account at ${APP_URL}/users/sign_up)"
fi
echo ""
echo -e "  Config:    $(pwd)/.env"
echo -e "  Stop:      docker compose -p ${COMPOSE_PROJECT} down"
echo -e "  Logs:      docker compose -p ${COMPOSE_PROJECT} logs -f web"
echo -e "  Restart:   docker compose -p ${COMPOSE_PROJECT} up -d"
echo ""
warn "Keep your .env file safe — it contains your secret tokens."
warn "To delete all data:  docker compose -p ${COMPOSE_PROJECT} down -v"
echo ""
